### ISSUE TITLE
Sync with Anki button does not appear

### ISSUE THREAD

**Issue by tonyhogsten** [pavelgordon/babbel2anki-chrome-extension#17]
Hello!

Is this project still maintained? I've followed the instructions as you've lined them out, but to me, the Sync with Anki button does not show up at all.

Anki versions:
Version ⁨2.1.52 (ab1c2395)⁩
Python 3.9.7 Qt 5.15.2 PyQt 5.15.5

Chrome version:
Version 102.0.5005.115 (Official Build) (64-bit)

Plugin version:
1.0.2

I've verified that http://[localhost:8765](http://localhost:8765/)/ gives me the response: AnkiConnect v.6

I have configured the AnkiConnect plugin with

```json
{
    "apiKey": null,
    "apiLogPath": null,
    "ignoreOriginList": [],
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOrigin": "http://localhost",
    "webCorsOriginList": [
        "*"
    ]
}
```

I'm not getting any clear errors in the console:

![image](https://user-images.githubusercontent.com/20438742/174866613-4b45f72a-708b-4136-9664-bed12abac5b5.png)

And for me Babbel looks like this:

![image](https://user-images.githubusercontent.com/20438742/174866732-d5ce521c-2532-4d90-8046-b161c5d8134c.png)

Is there any way you could help me out?

Thanks

**Comment by timpaulus** [comment]
Hello!

I can confirm that I had the same problem even after thoroughly following the installation steps in the README.

I decided to look into it and it seems that Babbel slightly changed the layout of the review manager page, including the html class names currently used to verify that the required html elements are loaded in the DOM before injecting the sync button.
At least this is my guess, since I don't know how the html looked before.

I slightly changed how the contentscript handles the new html class names and toolbar layout.
The sync button now appears for me.

I'm not sure if this is welcomed, but I created a pull request for the fix.
@pavelgordon Could you take a look at it and confirm the fix?

All the best

**Comment by Jannik098** [comment]
That would be awesome! I'm having the same issue!

**Comment by pavelgordon** [comment]
Hello! Thanks a lot for the contribution. Took a look and fix works, so i merged it, and will upload it to be available to be installed via Google Chrome Extensions once they approve it.

**Comment by wuqui** [comment]
Unfortunately, the sync button is gone for me now. It still worked fine yesterday. Maybe this is due to changes in Chrome? It would be great to have a fix, I use this extension every day.

Btw., thanks for making this extension 🙂

**Comment by timpaulus** [comment]
@pavelgordon The layout changed again and the html class names are now minimized/obfuscated by Babbel. I created a PR which fixes the issue by using an attribute selector. Could you take a look and maybe merge it again?

@wuqui If you need the fix urgently you can just download the master.zip from my fork and install the Extension manually :)

**Comment by wuqui** [comment]
> @wuqui If you need the fix urgently you can just download the master.zip from my fork and install the Extension manually :)

Thanks! Where can I find it?

**Comment by wuqui** [comment]
@timpaulus: I guess you meant `app.zip` instead of `master.zip`, right? I downloaded and installed it now, but the sync button still doesn’t appear. Maybe because Chrome shows an error for the plugin?

<img width="669" alt="image" src="https://github.com/pavelgordon/babbel2anki-chrome-extension/assets/8737499/715708dd-17eb-44c4-bf7f-3b97ec810bdb">

**Comment by epiwatson7** [comment]
@pavelgordon, sync to anki button is gone again. I think the layout of the Review page changed on Babel. can you tweak your extension pretty please?

**Comment by wuqui** [comment]
The above solution using the forked version by @timpaulus had worked for me until today. As of today, the sync button is gone again, unfortunately. Seems like Babbel changed it’s design and that made it disappear again. Could someone take care of this again or let me know how I can fix it myself, please? :)

**Comment by timpaulus** [comment]
Oof, shortly after my fix was merged into master... 😒
I quickly implemented another fix. Only a slight change was necessary.

@wuqui You can again install the extension by using my master branch:
https://github.com/timpaulus/babbel2anki-chrome-extension
After downloading the files, it is important that you **zip the app folder** yourself and add it manually as an extension. Do not use the existing app.zip!

@pavelgordon This is the third time a fix for the missing sync button is needed. I propose that the sync button is moved into the popup window of the extension. At least additionally to the existing solution. This way it's more stable against page layout changes from Babbel. What do you think? If you want I can implement it and create a PR.

Also, since Manifest V2 is deprecated by Google in June 2024, an update to Manifest V3 is soon necessary.
https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline
I don't know what your plans for this extension are and if you want to do an overhaul yourself. If you don't find the time I'd like to offer my help and migrate this extension. But since this will require major changes I first want to ask for permission to do so?

**Comment by wuqui** [comment]
> @wuqui You can again install the extension by using my master branch: https://github.com/timpaulus/babbel2anki-chrome-extension After downloading the files, it is important that you **zip the app folder** yourself and add it manually as an extension. Do not use the existing app.zip!

Thanks so much, it works! 🙂 

No need to zip the app folder, btw., one can simply do “load unpacked” in the extensions manager in Chrome.

**Comment by pavelgordon** [comment]
I will merge it today!

**Comment by wuqui** [comment]
The button is gone again, unfortunately 🫤

**Comment by pavelgordon** [comment]
> > The button is gone again, unfortunately 🫤
> 
> I created a pull request that fixes the issue :)

Merged, thanks! I will upload it to chrome as well, will take a day-two to approve them

**Comment by wuqui** [comment]
Great, thank you both!

**Comment by wromijn** [comment]
They changed the dom again. Created a PR
